name: Django_deploy

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install Miniconda
        run: |
          wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda.sh
          bash ~/miniconda.sh -b -p $HOME/miniconda
          source "$HOME/miniconda/etc/profile.d/conda.sh"
          conda init bash
          conda config --set auto_activate_base false
          conda env create -f environment.yaml

      - name: pull and reload on Aliyun
        run: |
          source "$HOME/miniconda/etc/profile.d/conda.sh"
          conda activate os-env
          sshpass -p ${{secrets.ECS_PASSWORD}} ssh -o StrictHostKeyChecking=no ${{secrets.ECS_USERNAME}}@${{secrets.ECS_IP}} "cd /usr; git clone https://github.com/ZPolister/SCAU-OS-Design.git; cd SCAU-OS-Design/os_djg; python kill.py; git pull --force; git checkout master; python manage.py runserver 0.0.0.0:8000;"

