name: Django Deploy

on:
  push:
    branches:
      - master  # 触发分支为 master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 检出代码仓库
      - name: Checkout repository
        uses: actions/checkout@v2

      # 部署到远程服务器
      - name: Deploy to Server
        env:
          ECS_USERNAME: ${{ secrets.ECS_USERNAME }}
          ECS_PASSWORD: ${{ secrets.ECS_PASSWORD }}
          ECS_IP: ${{ secrets.ECS_IP }}
        run: |
          sshpass -p ${{ secrets.ECS_PASSWORD }} ssh -o StrictHostKeyChecking=no ${{ secrets.ECS_USERNAME }}@${{ secrets.ECS_IP }} "
          set -x  # 开启调试
          cd /usr
          git clone https://github.com/ZPolister/SCAU-OS-Design.git
          cd SCAU-OS-Design/os_djg
          source ~/anaconda3/etc/profile.d/conda.sh  # 加载 Conda
          conda activate os-env            # 激活 os-env 环境
          git pull --force
          git checkout master
          
          # 获取所有 manage.py runserver 的进程号
          PIDS=$(pgrep -f 'manage.py runserver')
          
          # 检查是否找到进程
          if [ -n "$PIDS" ]; then
            echo "Found PIDs: $PIDS"
            
            # 循环处理每个 PID
            for pid in $PIDS; do
              # 检查进程是否仍在运行
              if ps -p $pid > /dev/null; then
                echo "Killing process $pid"
                kill -9 $pid  # 杀掉进程
                sleep 0.5     # 等待 0.5 秒
              else
                echo "Process $pid is not running"
              fi
            done
          else
            echo "No running manage.py runserver processes found."
          fi
          
          nohup python manage.py runserver 0.0.0.0:8000 > django_server.log 2>&1 &
          echo 'Django server started'
          "
