name: Django Deploy

on:
  push:
    branches:
      - master  # 触发分支为 master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 检出代码仓库
      - name: Checkout repository
        uses: actions/checkout@v2

      # 部署到远程服务器
      - name: Deploy to Server
        env:
          ECS_USERNAME: ${{ secrets.ECS_USERNAME }}
          ECS_PASSWORD: ${{ secrets.ECS_PASSWORD }}
          ECS_IP: ${{ secrets.ECS_IP }}
        run: |
          sshpass -p ${{ secrets.ECS_PASSWORD }} ssh -o StrictHostKeyChecking=no ${{ secrets.ECS_USERNAME }}@${{ secrets.ECS_IP }} "
          set -x  # 开启调试
          cd /usr
          git clone https://github.com/ZPolister/SCAU-OS-Design.git
          cd SCAU-OS-Design/os_djg
          source ~/anaconda3/etc/profile.d/conda.sh  # 加载 Conda
          conda activate os-env            # 激活 os-env 环境
          git pull --force
          git checkout master
          
          # 查找进程并输出 PID
          PIDS=\$(ps aux | grep 'manage.py runserver' | grep -v grep | awk '{print \$2}')
          echo "Found PIDs: \$PIDS"

          if [ -n "\$PIDS" ]; then
            for pid in \$PIDS; do
              if kill -9 \$pid; then
                echo "Killed process \$pid"
              else
                echo "Failed to kill process \$pid"
              fi
            done
          else
            echo 'No process found to kill'
          fi
          
          nohup python manage.py runserver 0.0.0.0:8000 &  # 后台运行
          echo 'Django server started'
          "
